### ISSUE TITLE
no https proxy support?

### ISSUE THREAD

**Issue by tessus** [gajus/global-agent#23]
I can only use a non TLS proxy, otherwise I get the following error:

```
UnexpectedStateError: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:"
```

However, who in 2020 uses a proxy via http? We can't expect companies to use an unencrypted proxy in their network, can we?

Can someone please explain to me how I can use a https or socks proxy with node?

**Comment by gajus** [comment]
> However, who in 2020 uses a proxy via http? We can't expect companies to use an unencrypted proxy in their network, can we?

Contributions are welcome.

Please note that if you use runtime generated SSL you will need to accept broken TLS, which defeats the purpose.

**Comment by tessus** [comment]
> Please note that if you use runtime generated SSL you will need to accept broken TLS,

This is not entirely true. The certs can't be verified, which doesn't mean the connection is insecure. More importantly, it's encrypted and not plain text.

Seriously, who uses a http proxy unless it's for testing?

**Comment by aviret** [comment]
> Seriously, who uses a http proxy unless it's for testing?

Our company ;-)

**Comment by gajus** [comment]
I cannot think of many reasonable use cases for needing a TLS between inner cluster nodes. If this network has been compromised, TLS is not going to help you.

**Comment by jmonster** [comment]
👋 I think there is a misunderstanding here about the actual role of a proxy. Please correct me if I'm wrong:

## TL;DR 
- an `http` proxy securely relays encrypted `https` messages between 2 peers
- `global-agent` does not support the additional `https` wrapper that would hide the headers of your `http` requests. Yet.

---

An `http` proxy can transmit an `https` connection between 2 peers; typical a client and a server. **The proxy cannot snoop on this traffic** if you've established a valid TLS exchange between those peers.

A nefarious/man-in-the-middle proxy interpreting your traffic would necessarily have to exchange certs with the client that do **not** match the domain in question (i.e. you don't know google.com's secret). i.e. your browser isn't vulnerable to this attack.

In order to snoop the proxy itself would have to connect to the upstream server and independently connect to the end user. In this scenario the proxy is more like a bridge between 2 connections -- it's not merely proxying messages, it's decrypting then re-encrypting them.

A very simple example is your ISP -- they are proxying everything from your home to the outbound server without making use of an additional encrypted wrapper.

**Comment by GammaPi** [comment]
There's some misunderstanding about tessus comments.
The background is this:
Someone tried to use global-agent in Joplin（a note taking app written in node.js）and submitted a pull request.
However, when testing with mitm-proxy (a man in the middle TLS proxy), tesus found that after enabling global-agent, Joplin won't realize that the certificate is self-signed and leaks user data.(I also did the test) If we don't use global-agent, then Joplin rejects to connect to websites with unsigned tls.

**Comment by GammaPi** [comment]
I found some clue, in ![HttpsProxyAgent.js](https://github.com/gajus/global-agent/blob/259865b2b2dfbf0d526bab063288c5eb797ca84d/src/classes/HttpsProxyAgent.js#L32) rejectUnauthorized: is hard coded as **false** rather than getting values from configuration file.

After setting this value to true, Joplin can realize the certificate is self-signed. Is this a security flas of global-agent? @gajus
