### ISSUE TITLE
Support traditional HTTP_PROXY, HTTPS_PROXY, NO_PROXY

### ISSUE THREAD

**Issue by rarkins** [gajus/global-agent#6]
It would be ideal if users *could* use global-agent in environments where users already use the traditional environment variables for proxy. Wouldn't it be safe to detect *both* the traditional as well as custom variables, with the custom ones taking precedence if both are present?

**Comment by gajus** [comment]
The problem is that once `HTTP_PROXY` variable is present, then certain libraries (e.g. `request`) configure their own HTTP proxy agent and override the default. If HTTP request is created using non-default agent then `global-agent` does not set agent, i.e. some requests will be handled using one proxy agent and some using another. This might just-work, but it might as well not work (because of different implementations) and it would be a very confusing issue to debug (e.g. NO_PROXY is non-standardised and could behave differently in requests handled by `global-agent` and other agents).

**Comment by rarkins** [comment]
So the problem is if the client library you're using (e.g. the package `request`) does its own agent transformation as well as `global-agent`?

I think these variables are as close as you can get to non-standardized standards. They are definitely what I'd consider "conventions". 

Anyway it's possible to check for the conventional variables and rewrite then for `global-agent`, but it seems unnecessary if pretty much all your users are doing that.

Perhaps leave this one open and see if over time there's any consensus?

Worse case, perhaps a GLOBAL_AGENT_CONVENTIONAL_ENV=true could be supported, to saving having to get/set three different variables?

**Comment by gajus** [comment]
You can now configure `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE`, e.g.

```bash
$ export GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=

```

See https://github.com/gajus/global-agent#what-is-the-reason-global-agentbootstrap-does-not-use-http_proxy

**Comment by rarkins** [comment]
Nice feature, thanks. Cc @fgreinacher
